// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commitdata.proto

package store

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// State commit information
type CommitData struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Version              int64    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitData) Reset()         { *m = CommitData{} }
func (m *CommitData) String() string { return proto.CompactTextString(m) }
func (*CommitData) ProtoMessage()    {}
func (*CommitData) Descriptor() ([]byte, []int) {
	return fileDescriptor_76ee1bd0c96bf4e9, []int{0}
}

func (m *CommitData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitData.Unmarshal(m, b)
}
func (m *CommitData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitData.Marshal(b, m, deterministic)
}
func (m *CommitData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitData.Merge(m, src)
}
func (m *CommitData) XXX_Size() int {
	return xxx_messageInfo_CommitData.Size(m)
}
func (m *CommitData) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitData.DiscardUnknown(m)
}

var xxx_messageInfo_CommitData proto.InternalMessageInfo

func (m *CommitData) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *CommitData) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*CommitData)(nil), "store.CommitData")
}

func init() { proto.RegisterFile("commitdata.proto", fileDescriptor_76ee1bd0c96bf4e9) }

var fileDescriptor_76ee1bd0c96bf4e9 = []byte{
	// 102 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xce, 0xcf, 0xcd,
	0xcd, 0x2c, 0x49, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x2e,
	0xc9, 0x2f, 0x4a, 0x55, 0xb2, 0xe2, 0xe2, 0x72, 0x06, 0x4b, 0xb9, 0x24, 0x96, 0x24, 0x0a, 0x09,
	0x71, 0xb1, 0x64, 0x24, 0x16, 0x67, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x81, 0xd9, 0x42,
	0x12, 0x5c, 0xec, 0x65, 0xa9, 0x45, 0xc5, 0x99, 0xf9, 0x79, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xcc,
	0x41, 0x30, 0x6e, 0x12, 0x1b, 0xd8, 0x24, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34, 0x07,
	0xce, 0xa2, 0x5d, 0x00, 0x00, 0x00,
}
