// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Transaction model across client and node.
//
// 'msg' is a []byte of application specific content,
// the application is reponsible for encoding/decoding it.
type Tx struct {
	Route                string   `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	Msg                  []byte   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Sender               []byte   `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Nonce                []byte   `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Sig                  []byte   `protobuf:"bytes,6,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (m *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(m, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *Tx) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Tx) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Tx) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Tx) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

// State commit information
type CommitInfo struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Version              int64    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitInfo) Reset()         { *m = CommitInfo{} }
func (m *CommitInfo) String() string { return proto.CompactTextString(m) }
func (*CommitInfo) ProtoMessage()    {}
func (*CommitInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *CommitInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitInfo.Unmarshal(m, b)
}
func (m *CommitInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitInfo.Marshal(b, m, deterministic)
}
func (m *CommitInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitInfo.Merge(m, src)
}
func (m *CommitInfo) XXX_Size() int {
	return xxx_messageInfo_CommitInfo.Size(m)
}
func (m *CommitInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CommitInfo proto.InternalMessageInfo

func (m *CommitInfo) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *CommitInfo) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*Tx)(nil), "types.Tx")
	proto.RegisterType((*CommitInfo)(nil), "types.CommitInfo")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xce, 0xbb, 0xca, 0xc2, 0x40,
	0x10, 0x05, 0x60, 0x36, 0xb7, 0x9f, 0x7f, 0x4c, 0x21, 0x83, 0xc8, 0x94, 0x21, 0x55, 0x2a, 0x1b,
	0x3b, 0x5b, 0x2b, 0xdb, 0xc5, 0x17, 0xf0, 0xb2, 0x26, 0x0b, 0x66, 0x27, 0xec, 0xac, 0xa2, 0x6f,
	0x2f, 0xd9, 0xd5, 0xee, 0x7c, 0x07, 0x0e, 0x33, 0xb0, 0x08, 0xef, 0xc9, 0xc8, 0x66, 0xf2, 0x1c,
	0x18, 0xcb, 0x88, 0xf6, 0x0e, 0xd9, 0xf1, 0x85, 0x2b, 0x28, 0x3d, 0x3f, 0x82, 0x21, 0xd5, 0xa8,
	0xee, 0x5f, 0x27, 0xe0, 0x12, 0xf2, 0x51, 0x7a, 0xca, 0x1b, 0xd5, 0xd5, 0x7a, 0x8e, 0xb8, 0x86,
	0x4a, 0x8c, 0xbb, 0x1a, 0x4f, 0x45, 0x2c, 0xbf, 0x9a, 0xf7, 0x8e, 0xdd, 0xc5, 0x50, 0x19, 0xeb,
	0x84, 0x79, 0x2f, 0xb6, 0xa7, 0x2a, 0xed, 0xc5, 0xf6, 0xed, 0x0e, 0x60, 0xcf, 0xe3, 0x68, 0xc3,
	0xc1, 0xdd, 0x18, 0x11, 0x8a, 0xe1, 0x24, 0x43, 0x3c, 0x5a, 0xeb, 0x98, 0x91, 0xe0, 0xef, 0x69,
	0xbc, 0x58, 0x76, 0x94, 0x35, 0xaa, 0xcb, 0xf5, 0x8f, 0xe7, 0x2a, 0xfe, 0xbd, 0xfd, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x90, 0x64, 0xa5, 0x9a, 0xc6, 0x00, 0x00, 0x00,
}
