// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Transaction model across client and node.
//
// 'msg' is a []byte of application specific content,
// the application is reponsible for encoding/decoding it.
type Tx struct {
	Route                string   `protobuf:"bytes,1,opt,name=route" json:"route,omitempty"`
	Msg                  []byte   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Sender               []byte   `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Nonce                uint64   `protobuf:"varint,5,opt,name=nonce" json:"nonce,omitempty"`
	Sig                  []byte   `protobuf:"bytes,6,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_4c15adb8b6351200, []int{0}
}
func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (dst *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(dst, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *Tx) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Tx) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Tx) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Tx) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

// State commit information
type CommitInfo struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Version              int64    `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitInfo) Reset()         { *m = CommitInfo{} }
func (m *CommitInfo) String() string { return proto.CompactTextString(m) }
func (*CommitInfo) ProtoMessage()    {}
func (*CommitInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_4c15adb8b6351200, []int{1}
}
func (m *CommitInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitInfo.Unmarshal(m, b)
}
func (m *CommitInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitInfo.Marshal(b, m, deterministic)
}
func (dst *CommitInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitInfo.Merge(dst, src)
}
func (m *CommitInfo) XXX_Size() int {
	return xxx_messageInfo_CommitInfo.Size(m)
}
func (m *CommitInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CommitInfo proto.InternalMessageInfo

func (m *CommitInfo) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *CommitInfo) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*Tx)(nil), "types.Tx")
	proto.RegisterType((*CommitInfo)(nil), "types.CommitInfo")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_types_4c15adb8b6351200) }

var fileDescriptor_types_4c15adb8b6351200 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xce, 0x3d, 0x8b, 0x02, 0x31,
	0x10, 0xc6, 0x71, 0xb2, 0x6f, 0xc7, 0xcd, 0x6d, 0x71, 0x0c, 0xc7, 0x31, 0x65, 0xd8, 0x2a, 0x95,
	0x8d, 0x9d, 0xad, 0x95, 0x6d, 0xf0, 0x0b, 0xf8, 0x12, 0x77, 0x03, 0x6e, 0x66, 0xc9, 0x44, 0xd1,
	0x6f, 0x2f, 0x9b, 0xd5, 0xee, 0xf9, 0x05, 0xfe, 0x64, 0xe0, 0x27, 0x3d, 0x27, 0x27, 0xab, 0x29,
	0x72, 0x62, 0xac, 0x33, 0xba, 0x2b, 0x14, 0xfb, 0x07, 0xfe, 0x41, 0x1d, 0xf9, 0x96, 0x1c, 0x29,
	0xad, 0xcc, 0xb7, 0x5d, 0x80, 0xbf, 0x50, 0x8e, 0xd2, 0x53, 0xa9, 0x95, 0x69, 0xed, 0x3c, 0xf1,
	0x1f, 0x1a, 0x71, 0xe1, 0xec, 0x22, 0x55, 0xf9, 0xf1, 0xad, 0xb9, 0x0f, 0x1c, 0x4e, 0x8e, 0x6a,
	0xad, 0x4c, 0x65, 0x17, 0xcc, 0xbd, 0xf8, 0x9e, 0x9a, 0xa5, 0x17, 0xdf, 0x77, 0x1b, 0x80, 0x2d,
	0x8f, 0xa3, 0x4f, 0xbb, 0x70, 0x61, 0x44, 0xa8, 0x86, 0x83, 0x0c, 0xf9, 0xd3, 0xd6, 0xe6, 0x8d,
	0x04, 0x5f, 0x77, 0x17, 0xc5, 0x73, 0xa0, 0x42, 0x2b, 0x53, 0xda, 0x0f, 0x8f, 0x4d, 0xbe, 0x7b,
	0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x5e, 0x94, 0x0d, 0xc6, 0x00, 0x00, 0x00,
}
